# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5832fa822e0f093dfa5fe691ce7b33831c829863578793475e13f8e219b6aba127646992d2bef87fc25d1b8ce491cd2693b377c6aeedf2b3383983037032026f

test:
  secret_key_base: 5f2a1f804538d865ffe63ed1f836c8337601e3fcb3d7afcbcc62c0a3af52534a2fc3b474112e7b1256d61fe18b880f61cb4cb9e101b63a3e68b54c8db96d97d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
